ALTER TABLE tools
ADD COLUMN IF NOT EXISTS custom_headers JSONB NOT NULL DEFAULT '{}',
ADD COLUMN IF NOT EXISTS request_in_body BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE tools
ALTER COLUMN schema SET DEFAULT '{}';